version: "3.7"

services:
  triton-redis:
    image: redis
    command: "redis-server /conf/redis.conf"
    ports:
      - '6379:6379'
    volumes:
      - ./certs:/tls
      - ./conf:/conf
  triton-server:
    links:
      -   triton-redis
    build:
      context: ../..
    command: tritonserver --cache-config redis,host=triton-redis --cache-config redis,port=6379 --cache-config redis,tls_enabled=true --cache-config redis,cert=/tls/redis.crt --cache-config redis,key=/tls/redis.key --cache-config redis,cacert=/tls/ca.crt --model-repository=/models
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8002:8002'
    volumes:
      - ../../../server/docs/examples/model_repository:/models
      - ./certs:/tls
