name: "CI"

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  tls:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: apt install -y rapidjson-dev
      - name: build
        run: sh ./build.sh
      - name: execute
        run: docker-compose -f ./examples/tls/docker-compose.yml run client